### PR TITLE
Added support for the IBAN bank account check

### PR DESCRIPTION
**Pull request by jvanbaarsen**
Added support for the IBAN bank account check.

The README still needs to change, will do that after you guys give the OK for the PR.

### CODE REVIEW

**Comment by ariejan** [comment]
Merged manually. 

I'm about to release elfproef-0.2.0, which will include these changes.

**Comment by jvanbaarsen** [comment]
What is the estimate for this release?

**Comment by ariejan** [comment]
@jvanbaarsen about 7 minutes ago http://rubygems.org/gems/elfproef :shipit:

**Comment by jvanbaarsen** [comment]
:+1:

**Pull request closed without merging**
